# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.AzureDataStudio
PackageVersion: 1.49.1
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Commands:
- azuredatastudio
ReleaseDate: 2024-08-14
Installers:
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-user-setup-1.49.1.exe
  InstallerSha256: D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2E3F4A5B6C7D8E9F0A1B2C3D4E5
  AppsAndFeaturesEntries:
  - ProductCode: '{2A3B4C5D-6E7F-8A9B-0C1D-2E3F4A5B6C7D}_is1'
    DisplayName: Azure Data Studio (User)
    Publisher: Microsoft Corporation
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe
  InstallerSha256: A9805DD11407F88810780CD03247EA31BD86E9E8CB14ED30776A704C38AD42B3
  AppsAndFeaturesEntries:
  - ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
    DisplayName: Azure Data Studio (User)
    Publisher: Microsoft Corporation
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-setup-1.49.1.exe
  InstallerSha256: 153A345F15F7CAB8BB5F95C6F485751DF0108C04906583D143E5ADC2AC6A21CC
  AppsAndFeaturesEntries:
  - ProductCode: '{6591F69E-6588-4980-81ED-C8FCBD7EC4B8}_is1'
    DisplayName: Azure Data Studio
    Publisher: Microsoft Corporation
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.6.0
